name: Build PHP Binary And Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: | 
          echo ${{ github.sha }} > release.txt
          echo ${{ secrets.WORKFLOW_TOKEN }} 
          whoami
          ls -lha
          ls -lha ~
          ls -lha /
          uname -a
          cat /etc/os-release
          free -h
          cat /proc/cpuinfo
          command -v docker
          pwd
          

      - name: Release Binary
        uses: softprops/action-gh-release@v2
        with:
          name: php
          tag_name: php
          files: |
            release.txt
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          overwrite_files: true
          token: ${{ secrets.WORKFLOW_TOKEN }}
